name: Build and Release ServicesChecker Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest

    env:
      Solution_Name: ServicesChecker.sln
      Project_Path: ServicesChecker/ServicesChecker.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Project_Path }}

    - name: Build application
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish application
      if: matrix.configuration == 'Release'
      run: dotnet publish ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --output ./publish --self-contained true -r win-x64 /p:PublishSingleFile=true

    - name: Create ZIP archive
      if: matrix.configuration == 'Release'
      shell: pwsh
      run: Compress-Archive -Path ./publish/* -DestinationPath ./ServicesChecker.zip -Force

    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: ServicesChecker-${{ matrix.configuration }}
        path: ./publish

    - name: Upload ZIP artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: ServicesChecker-ZIP
        path: ./ServicesChecker.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Set release version
      run: |
        echo "VERSION=$(date +'%Y.%m.%d').${{ github.run_number }}" >> $GITHUB_ENV

    - name: Download ZIP artifact
      uses: actions/download-artifact@v4
      with:
        name: ServicesChecker-ZIP

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: "ServicesChecker v${{ env.VERSION }}"
        body: "Release of ServicesChecker application."
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ServicesChecker.zip
        asset_name: ServicesChecker.zip
        asset_content_type: application/zip